In [1]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
dataframe_2=pd.read_csv("firstfile.csv",index_col=0)

dataframe_2.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [3]:
dataframe_2.tail()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
24996,0,0.376248,65,0,2471.000000,NaN,18,0,2,0,0.0
24997,0,0.165808,51,0,0.278066,7900.0,13,0,2,0,2.0
24998,0,0.047056,57,0,0.100115,7800.0,9,0,1,0,0.0
24999,0,0.257984,55,1,3058.000000,NaN,10,0,1,0,0.0
25000,0,0.503031,47,0,0.629975,8366.0,21,0,3,0,1.0

In [4]:
dataframe_2[dataframe_2.index.duplicated()]

Empty DataFrame
Columns: [SeriousDlqin2yrs, RevolvingUtilizationOfUnsecuredLines, age, NumberOfTime30-59DaysPastDueNotWorse, DebtRatio, MonthlyIncome, NumberOfOpenCreditLinesAndLoans, NumberOfTimes90DaysLate, NumberRealEstateLoansOrLines, NumberOfTime60-89DaysPastDueNotWorse, NumberOfDependents]
Index: []

In [5]:
dataframe_2.isnull().sum()

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                        0
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                           5008
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                       688
dtype: int64

In [6]:
final_df=dataframe_2.copy()

In [7]:
final_df.fillna(0)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
6,0,0.213179,74,0,0.375607,3500.0,3,0,1,0,1.0
7,0,0.305682,57,0,5710.000000,0.0,8,0,3,0,0.0
8,0,0.754464,39,0,0.209940,3500.0,8,0,0,0,0.0
9,0,0.116951,27,0,46.000000,0.0,2,0,0,0,0.0
10,0,0.189169,57,0,0.606291,23684.0,9,0,4,0,2.0
11,0,0.644226,30,0,0.309476,2500.0,5,0,0,0,0.0
12,0,0.018798,51,0,0.531529,6501.0,7,0,2,0,2.0
13,0,0.010352,46,0,0.298354,12454.0,13,0,2,0,2.0
14,1,0.964673,40,3,0.382965,13700.0,9,3,1,1,2.0
15,0,0.019657,76,0,477.000000,0.0,6,0,1,0,0.0
16,0,0.548458,64,0,0.209892,11362.0,7,0,1,0,2.0
17,0,0.061086,78,0,2058.000000,0.0,10,0,2,0,0.0
18,0,0.166284,53,0,0.188274,8800.0,7,0,0,0,0.0
19,0,0.221813,43,0,0.527888,3280.0,7,0,1,0,2.0
20,0,0.602794,25,0,0.065868,333.0,2,0,0,0,0.0
21,0,0.200923,43,0,0.430046,12300.0,10,0,2,0,0.0
22,1,0.025656,38,0,0.475841,3000.0,7,0,1,0,2.0
23,0,1.000000,39,0,0.241104,2500.0,4,0,0,0,0.0
24,0,0.075427,32,0,0.085512,7916.0,6,0,0,0,0.0
25,0,0.046560,58,0,0.241622,2416.0,9,0,1,0,0.0
26,1,0.392248,50,0,1.595253,4676.0,14,0,3,0,1.0
27,0,0.052436,58,0,0.097672,8333.0,22,0,1,0,0.0
28,0,0.034421,69,0,0.042383,2500.0,17,0,0,0,1.0
29,0,0.452516,24,0,0.011761,3400.0,1,0,0,0,0.0
30,0,0.392995,58,2,0.436103,5500.0,15,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
24971,1,0.991857,31,4,0.854458,2500.0,12,1,2,0,2.0
24972,0,1.000000,42,0,914.000000,0.0,3,0,1,0,1.0
24973,0,0.296181,50,2,0.186320,4765.0,9,1,0,0,0.0
24974,0,0.096083,66,0,0.175710,8200.0,6,0,2,0,1.0
24975,0,0.330422,28,1,0.448604,1468.0,9,0,0,0,0.0
24976,0,0.033585,72,0,1245.000000,0.0,6,0,0,0,0.0
24977,0,0.622659,53,0,0.135623,4600.0,5,0,0,0,1.0
24978,0,0.867674,49,0,0.653338,2800.0,7,0,1,0,4.0
24979,0,0.468221,60,0,0.442731,6093.0,7,0,1,0,0.0
24980,0,0.014384,41,1,0.185831,7000.0,10,0,2,0,3.0
24981,0,1.000000,65,0,0.000000,0.0,0,0,0,0,0.0
24982,0,0.138958,65,0,0.356660,3700.0,14,1,1,0,0.0
24983,0,0.036706,47,0,1409.000000,0.0,12,0,1,0,0.0
24984,0,0.889645,51,0,0.395434,6000.0,8,0,1,0,2.0
24985,0,0.820016,35,0,0.318168,10000.0,8,0,2,0,0.0
24986,1,0.864136,26,1,0.130623,3000.0,6,0,0,2,2.0
24987,0,0.645439,73,0,0.339705,1150.0,4,0,0,0,0.0
24988,0,0.138909,27,0,0.038756,2218.0,9,0,0,0,0.0
24989,0,0.000000,63,0,0.218908,12840.0,8,0,1,0,0.0
24990,0,0.860515,46,0,0.373078,8000.0,12,0,1,0,1.0
24991,0,0.312961,61,0,0.313478,11885.0,13,2,1,0,0.0
24992,0,0.011945,72,0,0.015441,1100.0,8,0,0,0,0.0
24993,0,0.247465,71,0,0.553312,4951.0,10,0,2,0,0.0
24994,0,0.130786,55,0,0.138037,34200.0,7,0,1,0,5.0
24995,0,0.255580,40,0,0.445620,2739.0,11,0,1,0,2.0
24996,0,0.376248,65,0,2471.000000,0.0,18,0,2,0,0.0
24997,0,0.165808,51,0,0.278066,7900.0,13,0,2,0,2.0
24998,0,0.047056,57,0,0.100115,7800.0,9,0,1,0,0.0
24999,0,0.257984,55,1,3058.000000,0.0,10,0,1,0,0.0
25000,0,0.503031,47,0,0.629975,8366.0,21,0,3,0,1.0

In [8]:
final_df=final_df.fillna(0)

In [9]:
final_df.isnull().sum()

SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

In [10]:
pred_df=final_df.copy()

In [11]:
pred_df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [12]:
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(pred_df, test_size=0.2, random_state=42)

In [13]:
train_set.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
23312,0,0.637687,60,0,0.250328,12183.0,9,0,1,0,0.0
23624,0,0.288493,31,0,0.072705,3300.0,3,0,0,0,0.0
1021,0,0.383952,35,0,0.498567,15000.0,18,0,2,0,0.0
12646,0,0.004541,73,0,5.000000,0.0,3,0,0,0,0.0
1534,0,0.063227,59,0,0.263462,13500.0,22,0,3,0,0.0

In [14]:
Train_X=train_set.drop(["SeriousDlqin2yrs"],axis=1)
Train_X.head()

,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
23312,0.637687,60,0,0.250328,12183.0,9,0,1,0,0.0
23624,0.288493,31,0,0.072705,3300.0,3,0,0,0,0.0
1021,0.383952,35,0,0.498567,15000.0,18,0,2,0,0.0
12646,0.004541,73,0,5.000000,0.0,3,0,0,0,0.0
1534,0.063227,59,0,0.263462,13500.0,22,0,3,0,0.0

In [15]:
Train_Y = train_set["SeriousDlqin2yrs"].copy()

In [16]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(Train_X,Train_Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
some_data = Train_X.iloc[6:14]
some_labels = Train_Y.iloc[6:14]
print("Predictions:\t",lin_reg.predict(some_data))

Predictions:	 [0.01893009 0.02587256 0.10621142 0.05241175 0.03271936 0.06412951
 0.12040703 0.03261514]

In [18]:
print("Labels\t\t",list(some_labels))

Labels		 [0, 0, 0, 0, 0, 0, 1, 0]

In [19]:
Test_X=test_set.drop(["SeriousDlqin2yrs"],axis=1)
Test_Y=test_set["SeriousDlqin2yrs"].copy()

from sklearn.metrics import mean_squared_error
loan_predictions = lin_reg.predict(Test_X)
lin_mse = mean_squared_error(Test_Y, loan_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.23755198640820377

In [20]:
from sklearn import linear_model
logreg = linear_model.LogisticRegression(C=1e5,max_iter=500)

In [21]:
logreg.fit(Train_X, Train_Y)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=500,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [22]:
print("Predictions:\t",logreg.predict(some_data))

Predictions:	 [0 0 0 0 0 0 0 0]

In [23]:
print("Labels\t\t",list(some_labels))

Labels		 [0, 0, 0, 0, 0, 0, 1, 0]

In [24]:
from sklearn.metrics import mean_squared_error
loan1_predictions = logreg.predict(Test_X)
lin_mse = mean_squared_error(Test_Y, loan1_predictions)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

0.2493992782667985

In [25]:
Test_X.head()

,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
6869,0.224248,56,0,0.800480,2500.0,19,0,1,0,0.0
24017,0.428807,57,0,0.115322,10500.0,8,0,0,0,0.0
9669,0.000781,85,0,0.222473,7083.0,5,0,1,0,0.0
13641,0.000435,79,0,0.394949,5701.0,15,0,3,0,0.0
14019,0.014451,61,0,3106.000000,0.0,12,0,3,0,0.0

In [26]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(Train_X,Train_Y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [27]:
Grade_predictions = tree_reg.predict(Test_X)
tree_mse = mean_squared_error(Test_Y, Grade_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.3168793145662872

In [28]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(tree_reg, Train_X, Train_Y, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)
rmse_scores.mean()

0.3170888145007974

In [29]:
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(Train_X,Train_Y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [30]:
scores = cross_val_score(forest_reg, Train_X, Train_Y, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

rmse_scores.mean()

0.23931173823616136

In [31]:
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(alpha=0.00001,epsilon=0.001,loss="epsilon_insensitive", penalty="l2", max_iter=500)
clf.fit(Train_X, Train_Y)

SGDClassifier(alpha=1e-05, average=False, class_weight=None, epsilon=0.001,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='epsilon_insensitive', max_iter=500,
       n_iter=None, n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [32]:
Grade_predictions = clf.predict(Test_X)
tree_mse = mean_squared_error(Test_Y, Grade_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.4783304297240559

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(Test_Y,loan1_predictions)

0.9378